// Package passage provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package passage

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for N400ErrorCode.
const (
	CustomProviderRequired N400ErrorCode = "custom_provider_required"
	InvalidRequest         N400ErrorCode = "invalid_request"
)

// Defines values for N401ErrorCode.
const (
	InvalidAccessToken N401ErrorCode = "invalid_access_token"
)

// Defines values for N404ErrorCode.
const (
	AdminNotFound              N404ErrorCode = "admin_not_found"
	ApiKeyNotFound             N404ErrorCode = "api_key_not_found"
	AppNotFound                N404ErrorCode = "app_not_found"
	DeviceNotFound             N404ErrorCode = "device_not_found"
	DomainNotFound             N404ErrorCode = "domain_not_found"
	EmailProviderNotFound      N404ErrorCode = "email_provider_not_found"
	EmailTemplateNotFound      N404ErrorCode = "email_template_not_found"
	EventNotFound              N404ErrorCode = "event_not_found"
	FunctionNotFound           N404ErrorCode = "function_not_found"
	FunctionSecretKeyNotFound  N404ErrorCode = "function_secret_key_not_found"
	FunctionVersionNotFound    N404ErrorCode = "function_version_not_found"
	MetadataFieldNotFound      N404ErrorCode = "metadata_field_not_found"
	Oauth2AppNotFound          N404ErrorCode = "oauth2_app_not_found"
	OrganizationMemberNotFound N404ErrorCode = "organization_member_not_found"
	SmsProviderNotFound        N404ErrorCode = "sms_provider_not_found"
	SmsTemplateNotFound        N404ErrorCode = "sms_template_not_found"
	SocialConnectionNotFound   N404ErrorCode = "social_connection_not_found"
	UserNotFound               N404ErrorCode = "user_not_found"
)

// Defines values for N500ErrorCode.
const (
	InternalServerError N500ErrorCode = "internal_server_error"
)

// Defines values for AppInfoType.
const (
	AppInfoTypeComplete AppInfoType = "complete"
	AppInfoTypeFlex     AppInfoType = "flex"
)

// Defines values for FontFamily.
const (
	AndaléMono    FontFamily = "Andalé Mono"
	Arial         FontFamily = "Arial"
	ArialBlack    FontFamily = "Arial Black"
	Baskerville   FontFamily = "Baskerville"
	BradleyHand   FontFamily = "Bradley Hand"
	BrushScriptMT FontFamily = "Brush Script MT"
	ComicSansMS   FontFamily = "Comic Sans MS"
	Courier       FontFamily = "Courier"
	Georgia       FontFamily = "Georgia"
	GillSans      FontFamily = "Gill Sans"
	Helvetica     FontFamily = "Helvetica"
	Impact        FontFamily = "Impact"
	Lucida        FontFamily = "Lucida"
	Luminari      FontFamily = "Luminari"
	Monaco        FontFamily = "Monaco"
	Palatino      FontFamily = "Palatino"
	Tahoma        FontFamily = "Tahoma"
	TimesNewRoman FontFamily = "Times New Roman"
	TrebuchetMS   FontFamily = "Trebuchet MS"
	Verdana       FontFamily = "Verdana"
)

// Defines values for MagicLinkChannel.
const (
	EmailChannel ChannelType = "email"
	PhoneChannel ChannelType = "phone"
)

// Defines values for MagicLinkType.
const (
	LoginType            MagicLinkType = "login"
	VerifyIdentifierType MagicLinkType = "verify_identifier"
)

// Defines values for Technologies.
const (
	Android    Technologies = "android"
	Angular    Technologies = "angular"
	Go         Technologies = "go"
	Ios        Technologies = "ios"
	Javascript Technologies = "javascript"
	Python     Technologies = "python"
	React      Technologies = "react"
	Vue        Technologies = "vue"
)

// Defines values for TTLDisplayUnit.
const (
	D TTLDisplayUnit = "d"
	H TTLDisplayUnit = "h"
	M TTLDisplayUnit = "m"
	S TTLDisplayUnit = "s"
)

// Defines values for UserEventStatus.
const (
	UserEventStatusComplete   UserEventStatus = "complete"
	UserEventStatusIncomplete UserEventStatus = "incomplete"
)

// Defines values for UserMetadataFieldType.
const (
	BooleanMD UserMetadataFieldType = "boolean"
	DateMD    UserMetadataFieldType = "date"
	EmailMD   UserMetadataFieldType = "email"
	IntegerMD UserMetadataFieldType = "integer"
	PhoneMD   UserMetadataFieldType = "phone"
	StringMD  UserMetadataFieldType = "string"
)

// Defines values for UserStatus.
const (
	StatusActive   UserStatus = "active"
	StatusInactive UserStatus = "inactive"
	StatusPending  UserStatus = "pending"
)

// Defines values for WebAuthnType.
const (
	Passkey     WebAuthnType = "passkey"
	Platform    WebAuthnType = "platform"
	SecurityKey WebAuthnType = "security_key"
)

// N400Error defines model for 400Error.
type N400Error struct {
	Code  N400ErrorCode `json:"code"`
	Error string        `json:"error"`
}

// N400ErrorCode defines model for 400Error.Code.
type N400ErrorCode string

// N401Error defines model for 401Error.
type N401Error struct {
	Code  N401ErrorCode `json:"code"`
	Error string        `json:"error"`
}

// N401ErrorCode defines model for 401Error.Code.
type N401ErrorCode string

// N404Error defines model for 404Error.
type N404Error struct {
	Code  N404ErrorCode `json:"code"`
	Error string        `json:"error"`
}

// N404ErrorCode defines model for 404Error.Code.
type N404ErrorCode string

// N500Error defines model for 500Error.
type N500Error struct {
	Code  N500ErrorCode `json:"code"`
	Error string        `json:"error"`
}

// N500ErrorCode defines model for 500Error.Code.
type N500ErrorCode string

// AppInfo defines model for AppInfo.
type AppInfo struct {
	AdditionalAuthOrigins []string `json:"additional_auth_origins"`

	// AllowedCallbackURLs The valid URLs where users can be redirected after authentication.
	AllowedCallbackURLs []string `json:"allowed_callback_urls"`
	AllowedIdentifier   string   `json:"allowed_identifier"`

	// AllowedLogoutURLs The valid URLs where users can be redirected after logging out.
	AllowedLogoutURLs []string `json:"allowed_logout_urls"`

	// ApplicationLoginURI A route within your application that redirects to the Authorization URL endpoint.
	ApplicationLoginURI string `json:"application_login_uri"`

	// AuthFallbackMethod Deprecated Property. Please refer to `auth_methods` to view settings for individual authentication methods.
	// Deprecated:
	AuthFallbackMethod string `json:"auth_fallback_method"`

	// AuthFallbackMethodTTL Deprecated Property. Please refer to `auth_methods` to view settings for individual authentication methods.
	// Deprecated:
	AuthFallbackMethodTTL int `json:"auth_fallback_method_ttl"`

	// AuthMethods Denotes what methods this app is allowed to use for authentication with configurations
	AuthMethods              AuthMethods          `json:"auth_methods"`
	AuthOrigin               string               `json:"auth_origin"`
	CreatedAt                time.Time            `json:"created_at"`
	DarkLogoURL              *string              `json:"dark_logo_url,omitempty"`
	DefaultLanguage          string               `json:"default_language"`
	ElementCustomization     ElementCustomization `json:"element_customization"`
	ElementCustomizationDark ElementCustomization `json:"element_customization_dark"`

	// Hosted whether or not the app's login page hosted by passage
	Hosted bool `json:"hosted"`

	// HostedSubdomain the subdomain of the app's hosted login page
	HostedSubdomain               string  `json:"hosted_subdomain"`
	ID                            string  `json:"id"`
	IDTokenLifetime               *int    `json:"id_token_lifetime,omitempty"`
	Layouts                       Layouts `json:"layouts"`
	LightLogoURL                  *string `json:"light_logo_url,omitempty"`
	LoginURL                      string  `json:"login_url"`
	Name                          string  `json:"name"`
	PassageBranding               bool    `json:"passage_branding"`
	ProfileManagement             bool    `json:"profile_management"`
	PublicSignup                  bool    `json:"public_signup"`
	RedirectURL                   string  `json:"redirect_url"`
	RefreshAbsoluteLifetime       int     `json:"refresh_absolute_lifetime"`
	RefreshEnabled                bool    `json:"refresh_enabled"`
	RefreshInactivityLifetime     int     `json:"refresh_inactivity_lifetime"`
	RequireEmailVerification      bool    `json:"require_email_verification"`
	RequireIdentifierVerification bool    `json:"require_identifier_verification"`
	RequiredIdentifier            string  `json:"required_identifier"`
	Role                          string  `json:"role"`
	RSAPublicKey                  string  `json:"rsa_public_key"`

	// Secret can only be retrieved by an app admin
	Secret               *string             `json:"secret,omitempty"`
	SessionTimeoutLength int                 `json:"session_timeout_length"`
	Technologies         []Technologies      `json:"technologies"`
	Type                 AppInfoType         `json:"type"`
	UserMetadataSchema   []UserMetadataField `json:"user_metadata_schema"`
}

// AppInfoType defines model for AppInfo.Type.
type AppInfoType string

// AppResponse defines model for AppResponse.
type AppResponse struct {
	App AppInfo `json:"app"`
}

// AppleUserSocialConnection defines model for AppleUserSocialConnection.
type AppleUserSocialConnection struct {
	CreatedAt   time.Time `json:"created_at"`
	LastLoginAt time.Time `json:"last_login_at"`

	// ProviderID The external ID of the Social Connection.
	ProviderID string `json:"provider_id"`

	// ProviderIdentifier The email of connected social user.
	ProviderIdentifier string `json:"provider_identifier"`
}

// AuthMethods Denotes what methods this app is allowed to use for authentication with configurations
type AuthMethods struct {
	MagicLink MagicLinkAuthMethod `json:"magic_link"`
	Otp       OtpAuthMethod       `json:"otp"`
	Passkeys  PasskeysAuthMethod  `json:"passkeys"`
}

// CreateMagicLinkBody defines model for CreateMagicLinkBody.
type CreateMagicLinkBody struct {
	Channel ChannelType `json:"channel"`
	Email   string      `json:"email"`

	// Language language of the email to send (optional)
	Language      string        `json:"language,omitempty"`
	MagicLinkPath string        `json:"magic_link_path"`
	Phone         string        `json:"phone"`
	RedirectURL   string        `json:"redirect_url"`
	Send          bool          `json:"send"`
	TTL           int           `json:"ttl"`
	Type          MagicLinkType `json:"type,omitempty"`
	UserID        string        `json:"user_id"`
}

// CreateUserBody defines model for CreateUserBody.
type CreateUserBody struct {
	// Email Email of the new user. Either this or `phone` is required; both may be provided.
	Email string `json:"email,omitempty"`

	// Phone Phone number of the new user. Either this or `email` is required; both may be provided.
	Phone        string                 `json:"phone,omitempty"`
	UserMetadata map[string]interface{} `json:"user_metadata,omitempty"`
}

// ElementCustomization defines model for ElementCustomization.
type ElementCustomization struct {
	// PassageBodyFontFamily Body font family
	PassageBodyFontFamily *FontFamily `json:"passage_body_font_family,omitempty"`

	// PassageBodyTextColor Body text color in hex.
	// Default is `#222222` in light mode & `#f3f3f3` in dark mode.
	PassageBodyTextColor *string `json:"passage_body_text_color,omitempty"`

	// PassageContainerBackgroundColor Container background color in hex.
	// Default is `#ffffff` in light mode & `#383838` in dark mode.
	PassageContainerBackgroundColor *string `json:"passage_container_background_color,omitempty"`

	// PassageContainerMaxWidth Maximum width of container (px)
	PassageContainerMaxWidth *int `json:"passage_container_max_width,omitempty"`

	// PassageHeaderFontFamily Body font family
	PassageHeaderFontFamily *FontFamily `json:"passage_header_font_family,omitempty"`

	// PassageHeaderTextColor Header text color in hex.
	// Default is `#222222` in light mode & `#f3f3f3` in dark mode.
	PassageHeaderTextColor *string `json:"passage_header_text_color,omitempty"`

	// PassageInputBoxBackgroundColor Input box background color in hex.
	// Default is `#ffffff` in light mode & `#4b4b4b` in dark mode.
	PassageInputBoxBackgroundColor *string `json:"passage_input_box_background_color,omitempty"`

	// PassageInputBoxBorderRadius Input box border radius (px)
	PassageInputBoxBorderRadius *int `json:"passage_input_box_border_radius,omitempty"`

	// PassagePrimaryButtonBackgroundColor Primary button background colour (hex)
	PassagePrimaryButtonBackgroundColor *string `json:"passage_primary_button_background_color,omitempty"`

	// PassagePrimaryButtonBorderColor Primary button border color
	PassagePrimaryButtonBorderColor *string `json:"passage_primary_button_border_color,omitempty"`

	// PassagePrimaryButtonBorderRadius Primary button border radius (px)
	PassagePrimaryButtonBorderRadius *int `json:"passage_primary_button_border_radius,omitempty"`

	// PassagePrimaryButtonBorderWidth Primary button border width (px)
	PassagePrimaryButtonBorderWidth *int `json:"passage_primary_button_border_width,omitempty"`

	// PassagePrimaryButtonHoverColor Primary button background on hover (hex)
	PassagePrimaryButtonHoverColor *string `json:"passage_primary_button_hover_color,omitempty"`

	// PassagePrimaryButtonTextColor Primary button font colour (hex)
	PassagePrimaryButtonTextColor *string `json:"passage_primary_button_text_color,omitempty"`

	// PassageSecondaryButtonBackgroundColor Secondary button background colour (hex)
	PassageSecondaryButtonBackgroundColor *string `json:"passage_secondary_button_background_color,omitempty"`

	// PassageSecondaryButtonBorderColor Secondary button border color
	PassageSecondaryButtonBorderColor *string `json:"passage_secondary_button_border_color,omitempty"`

	// PassageSecondaryButtonBorderRadius Secondary button border radius (px)
	PassageSecondaryButtonBorderRadius *int `json:"passage_secondary_button_border_radius,omitempty"`

	// PassageSecondaryButtonBorderWidth Secondary button border width (px)
	PassageSecondaryButtonBorderWidth *int `json:"passage_secondary_button_border_width,omitempty"`

	// PassageSecondaryButtonHoverColor Secondary button background on hover (hex)
	PassageSecondaryButtonHoverColor *string `json:"passage_secondary_button_hover_color,omitempty"`

	// PassageSecondaryButtonTextColor Secondary button font colour (hex)
	PassageSecondaryButtonTextColor *string `json:"passage_secondary_button_text_color,omitempty"`
}

// FontFamily Body font family
type FontFamily string

// GithubUserSocialConnection defines model for GithubUserSocialConnection.
type GithubUserSocialConnection struct {
	CreatedAt   time.Time `json:"created_at"`
	LastLoginAt time.Time `json:"last_login_at"`

	// ProviderID The external ID of the Social Connection.
	ProviderID string `json:"provider_id"`

	// ProviderIdentifier The email of connected social user.
	ProviderIdentifier string `json:"provider_identifier"`
}

// GoogleUserSocialConnection defines model for GoogleUserSocialConnection.
type GoogleUserSocialConnection struct {
	CreatedAt   time.Time `json:"created_at"`
	LastLoginAt time.Time `json:"last_login_at"`

	// ProviderID The external ID of the Social Connection.
	ProviderID string `json:"provider_id"`

	// ProviderIdentifier The email of connected social user.
	ProviderIdentifier string `json:"provider_identifier"`
}

// LayoutConfig defines model for LayoutConfig.
type LayoutConfig struct {
	H  int    `json:"h"`
	ID string `json:"id"`
	W  int    `json:"w"`
	X  int    `json:"x"`
	Y  int    `json:"y"`
}

// Layouts defines model for Layouts.
type Layouts struct {
	Profile      []LayoutConfig `json:"profile"`
	Registration []LayoutConfig `json:"registration"`
}

// ListDevicesResponse defines model for ListDevicesResponse.
type ListDevicesResponse struct {
	Devices []WebAuthnDevices `json:"devices"`
}

// MagicLink defines model for MagicLink.
type MagicLink struct {
	Activated   bool          `json:"activated"`
	AppID       string        `json:"app_id"`
	ID          string        `json:"id"`
	Identifier  string        `json:"identifier"`
	RedirectURL string        `json:"redirect_url"`
	Secret      string        `json:"secret"`
	TTL         int           `json:"ttl"`
	Type        MagicLinkType `json:"type"`
	URL         string        `json:"url"`
	UserID      string        `json:"user_id"`
}

// MagicLinkAuthMethod defines model for MagicLinkAuthMethod.
type MagicLinkAuthMethod struct {
	Enabled bool `json:"enabled"`

	// TTL Maximum time (IN SECONDS) for the auth to expire.
	TTL int `json:"ttl"`

	// TTLDisplayUnit Deprecated Property. The preferred unit for displaying the TTL. This value is for display only.
	// * `s` - seconds
	// * `m` - minutes
	// * `h` - hours
	// * `d` - days
	// Deprecated:
	TTLDisplayUnit TTLDisplayUnit `json:"ttl_display_unit"`
}

// ChannelType defines model for ChannelType.
type ChannelType string

// MagicLinkResponse defines model for MagicLinkResponse.
type MagicLinkResponse struct {
	MagicLink MagicLink `json:"magic_link"`
}

// MagicLinkType defines model for MagicLinkType.
type MagicLinkType string

// OtpAuthMethod defines model for OtpAuthMethod.
type OtpAuthMethod struct {
	Enabled bool `json:"enabled"`

	// TTL Maximum time (IN SECONDS) for the auth to expire.
	TTL int `json:"ttl"`

	// TTLDisplayUnit Deprecated Property. The preferred unit for displaying the TTL. This value is for display only.
	// * `s` - seconds
	// * `m` - minutes
	// * `h` - hours
	// * `d` - days
	// Deprecated:
	TTLDisplayUnit TTLDisplayUnit `json:"ttl_display_unit"`
}

// PasskeysAuthMethod defines model for PasskeysAuthMethod.
type PasskeysAuthMethod struct {
	Enabled bool `json:"enabled"`
}

// Technologies defines model for Technologies.
type Technologies string

// TTLDisplayUnit Deprecated Property. The preferred unit for displaying the TTL. This value is for display only.
// * `s` - seconds
// * `m` - minutes
// * `h` - hours
// * `d` - days
type TTLDisplayUnit string

// UpdateMagicLinkAuthMethod defines model for UpdateMagicLinkAuthMethod.
type UpdateMagicLinkAuthMethod struct {
	Enabled *bool `json:"enabled,omitempty"`

	// TTL Maximum time (IN SECONDS) for the auth to expire.
	TTL *int `json:"ttl,omitempty"`

	// TTLDisplayUnit Deprecated Property. The preferred unit for displaying the TTL. This value is for display only.
	// * `s` - seconds
	// * `m` - minutes
	// * `h` - hours
	// * `d` - days
	// Deprecated:
	TTLDisplayUnit *TTLDisplayUnit `json:"ttl_display_unit,omitempty"`
}

// UpdateOtpAuthMethod defines model for UpdateOtpAuthMethod.
type UpdateOtpAuthMethod struct {
	Enabled *bool `json:"enabled,omitempty"`

	// TTL Maximum time (IN SECONDS) for the auth to expire.
	TTL *int `json:"ttl,omitempty"`

	// TTLDisplayUnit Deprecated Property. The preferred unit for displaying the TTL. This value is for display only.
	// * `s` - seconds
	// * `m` - minutes
	// * `h` - hours
	// * `d` - days
	// Deprecated:
	TTLDisplayUnit *TTLDisplayUnit `json:"ttl_display_unit,omitempty"`
}

// UpdatePasskeysAuthMethod defines model for UpdatePasskeysAuthMethod.
type UpdatePasskeysAuthMethod struct {
	Enabled *bool `json:"enabled,omitempty"`
}

// UpdateBody defines model for UpdateBody.
type UpdateBody struct {
	Email        string                 `json:"email,omitempty"`
	Phone        string                 `json:"phone,omitempty"`
	UserMetadata map[string]interface{} `json:"user_metadata,omitempty"`
}

// UserEventStatus defines model for UserEventStatus.
type UserEventStatus string

// User defines model for User.
type User struct {
	CreatedAt         time.Time              `json:"created_at"`
	Email             string                 `json:"email"`
	EmailVerified     bool                   `json:"email_verified"`
	ID                string                 `json:"id"`
	LastLoginAt       time.Time              `json:"last_login_at"`
	LoginCount        int                    `json:"login_count"`
	Phone             string                 `json:"phone"`
	PhoneVerified     bool                   `json:"phone_verified"`
	RecentEvents      []UserRecentEvent      `json:"recent_events"`
	SocialConnections UserSocialConnections  `json:"social_connections"`
	Status            UserStatus             `json:"status"`
	UpdatedAt         time.Time              `json:"updated_at"`
	UserMetadata      map[string]interface{} `json:"user_metadata"`
	Webauthn          bool                   `json:"webauthn"`
	WebauthnDevices   []WebAuthnDevices      `json:"webauthn_devices"`

	// WebauthnTypes List of credential types that have been used for authentication
	WebauthnTypes []WebAuthnType `json:"webauthn_types"`
}

// UserMetadataField defines model for UserMetadataField.
type UserMetadataField struct {
	FieldName    string                `json:"field_name"`
	FriendlyName string                `json:"friendly_name"`
	ID           string                `json:"id"`
	Profile      bool                  `json:"profile"`
	Registration bool                  `json:"registration"`
	Type         UserMetadataFieldType `json:"type"`
}

// UserMetadataFieldType defines model for UserMetadataFieldType.
type UserMetadataFieldType string

// UserRecentEvent defines model for UserRecentEvent.
type UserRecentEvent struct {
	CompletedAt *time.Time      `json:"completed_at"`
	CreatedAt   time.Time       `json:"created_at"`
	ID          string          `json:"id"`
	IPAddr      string          `json:"ip_addr"`
	Status      UserEventStatus `json:"status"`
	Type        string          `json:"type"`
	UserAgent   string          `json:"user_agent"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	User User `json:"user"`
}

// UserSocialConnections defines model for UserSocialConnections.
type UserSocialConnections struct {
	Apple  *AppleUserSocialConnection  `json:"apple,omitempty"`
	Github *GithubUserSocialConnection `json:"github,omitempty"`
	Google *GoogleUserSocialConnection `json:"google,omitempty"`
}

// UserStatus defines model for UserStatus.
type UserStatus string

// WebAuthnDevices defines model for WebAuthnDevices.
type WebAuthnDevices struct {
	// CreatedAt The first time this webAuthn device was used to authenticate the user
	CreatedAt time.Time `json:"created_at"`

	// CredID The CredID for this webAuthn device
	CredID string `json:"cred_id"`

	// FriendlyName The friendly name for the webAuthn device used to authenticate
	FriendlyName string `json:"friendly_name"`

	// Icons Contains the light and dark SVG icons that represent the brand of those devices
	// Values can be null or base64 encoded SVG. Example of SVG output:
	// data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIGVuYWJsZS1iYWNrZ3JvdW5kPSJuZXcgMCAwIDE5MiAxOTIiIGhlaWdodD0iMjRweCIgdmlld0JveD0iMCAwIDE5MiAxOTIiIHdpZHRoPSIyNHB4Ij48cmVjdCBmaWxsPSJub25lIiBoZWlnaHQ9IjE5MiIgd2lkdGg9IjE5MiIgeT0iMCIvPjxnPjxwYXRoIGQ9Ik02OS4yOSwxMDZjLTMuNDYsNS45Ny05LjkxLDEwLTE3LjI5LDEwYy0xMS4wMywwLTIwLTguOTctMjAtMjBzOC45Ny0yMCwyMC0yMCBjNy4zOCwwLDEzLjgzLDQuMDMsMTcuMjksMTBoMjUuNTVDOTAuMyw2Ni41NCw3Mi44Miw1Miw1Miw1MkMyNy43NCw1Miw4LDcxLjc0LDgsOTZzMTkuNzQsNDQsNDQsNDRjMjAuODIsMCwzOC4zLTE0LjU0LDQyLjg0LTM0IEg2OS4yOXoiIGZpbGw9IiM0Mjg1RjQiLz48cmVjdCBmaWxsPSIjRkJCQzA0IiBoZWlnaHQ9IjI0IiB3aWR0aD0iNDQiIHg9Ijk0IiB5PSI4NCIvPjxwYXRoIGQ9Ik05NC4zMiw4NEg2OHYwLjA1YzIuNSwzLjM0LDQsNy40Nyw0LDExLjk1cy0xLjUsOC42MS00LDExLjk1VjEwOGgyNi4zMiBjMS4wOC0zLjgyLDEuNjgtNy44NCwxLjY4LTEyUzk1LjQxLDg3LjgyLDk0LjMyLDg0eiIgZmlsbD0iI0VBNDMzNSIvPjxwYXRoIGQ9Ik0xODQsMTA2djI2aC0xNnYtOGMwLTQuNDItMy41OC04LTgtOHMtOCwzLjU4LTgsOHY4aC0xNnYtMjZIMTg0eiIgZmlsbD0iIzM0QTg1MyIvPjxyZWN0IGZpbGw9IiMxODgwMzgiIGhlaWdodD0iMjQiIHdpZHRoPSI0OCIgeD0iMTM2IiB5PSI4NCIvPjwvZz48L3N2Zz4=
	Icons WebAuthnIcons `json:"icons"`

	// ID The ID of the webAuthn device used for authentication
	ID string `json:"id"`

	// LastLoginAt The last time this webAuthn device was used to authenticate the user
	LastLoginAt time.Time `json:"last_login_at"`

	// Type The type of this credential
	Type WebAuthnType `json:"type"`

	// UpdatedAt The last time this webAuthn device was updated
	UpdatedAt time.Time `json:"updated_at"`

	// UsageCount How many times this webAuthn device has been used to authenticate the user
	UsageCount int `json:"usage_count"`
}

// WebAuthnIcons Contains the light and dark SVG icons that represent the brand of those devices
// Values can be null or base64 encoded SVG. Example of SVG output:
// data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIGVuYWJsZS1iYWNrZ3JvdW5kPSJuZXcgMCAwIDE5MiAxOTIiIGhlaWdodD0iMjRweCIgdmlld0JveD0iMCAwIDE5MiAxOTIiIHdpZHRoPSIyNHB4Ij48cmVjdCBmaWxsPSJub25lIiBoZWlnaHQ9IjE5MiIgd2lkdGg9IjE5MiIgeT0iMCIvPjxnPjxwYXRoIGQ9Ik02OS4yOSwxMDZjLTMuNDYsNS45Ny05LjkxLDEwLTE3LjI5LDEwYy0xMS4wMywwLTIwLTguOTctMjAtMjBzOC45Ny0yMCwyMC0yMCBjNy4zOCwwLDEzLjgzLDQuMDMsMTcuMjksMTBoMjUuNTVDOTAuMyw2Ni41NCw3Mi44Miw1Miw1Miw1MkMyNy43NCw1Miw4LDcxLjc0LDgsOTZzMTkuNzQsNDQsNDQsNDRjMjAuODIsMCwzOC4zLTE0LjU0LDQyLjg0LTM0IEg2OS4yOXoiIGZpbGw9IiM0Mjg1RjQiLz48cmVjdCBmaWxsPSIjRkJCQzA0IiBoZWlnaHQ9IjI0IiB3aWR0aD0iNDQiIHg9Ijk0IiB5PSI4NCIvPjxwYXRoIGQ9Ik05NC4zMiw4NEg2OHYwLjA1YzIuNSwzLjM0LDQsNy40Nyw0LDExLjk1cy0xLjUsOC42MS00LDExLjk1VjEwOGgyNi4zMiBjMS4wOC0zLjgyLDEuNjgtNy44NCwxLjY4LTEyUzk1LjQxLDg3LjgyLDk0LjMyLDg0eiIgZmlsbD0iI0VBNDMzNSIvPjxwYXRoIGQ9Ik0xODQsMTA2djI2aC0xNnYtOGMwLTQuNDItMy41OC04LTgtOHMtOCwzLjU4LTgsOHY4aC0xNnYtMjZIMTg0eiIgZmlsbD0iIzM0QTg1MyIvPjxyZWN0IGZpbGw9IiMxODgwMzgiIGhlaWdodD0iMjQiIHdpZHRoPSI0OCIgeD0iMTM2IiB5PSI4NCIvPjwvZz48L3N2Zz4=
type WebAuthnIcons struct {
	Dark  *string `json:"dark"`
	Light *string `json:"light"`
}

// WebAuthnType The type of this credential
type WebAuthnType string

// AppID defines model for app_id.
type AppID = string

// UserID defines model for user_id.
type UserID = string

// CreateMagicLinkJSONRequestBody defines body for CreateMagicLink for application/json ContentType.
type CreateMagicLinkJSONRequestBody = CreateMagicLinkBody

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = CreateUserBody

// UpdateUserJSONRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody = UpdateBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetApp request
	GetApp(ctx context.Context, appID AppID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateMagicLinkWithBody request with any body
	CreateMagicLinkWithBody(ctx context.Context, appID AppID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateMagicLink(ctx context.Context, appID AppID, body CreateMagicLinkJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateUserWithBody request with any body
	CreateUserWithBody(ctx context.Context, appID AppID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateUser(ctx context.Context, appID AppID, body CreateUserJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteUser request
	DeleteUser(ctx context.Context, appID AppID, userID UserID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetUser request
	GetUser(ctx context.Context, appID AppID, userID UserID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateUserWithBody request with any body
	UpdateUserWithBody(ctx context.Context, appID AppID, userID UserID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdateUser(ctx context.Context, appID AppID, userID UserID, body UpdateUserJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ActivateUser request
	ActivateUser(ctx context.Context, appID AppID, userID UserID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeactivateUser request
	DeactivateUser(ctx context.Context, appID AppID, userID UserID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListUserDevices request
	ListUserDevices(ctx context.Context, appID AppID, userID UserID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteUserDevices request
	DeleteUserDevices(ctx context.Context, appID AppID, userID UserID, deviceID string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RevokeUserRefreshTokens request
	RevokeUserRefreshTokens(ctx context.Context, appID AppID, userID UserID, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetApp(ctx context.Context, appID AppID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAppRequest(c.Server, appID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateMagicLinkWithBody(ctx context.Context, appID AppID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateMagicLinkRequestWithBody(c.Server, appID, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateMagicLink(ctx context.Context, appID AppID, body CreateMagicLinkJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateMagicLinkRequest(c.Server, appID, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateUserWithBody(ctx context.Context, appID AppID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateUserRequestWithBody(c.Server, appID, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateUser(ctx context.Context, appID AppID, body CreateUserJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateUserRequest(c.Server, appID, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteUser(ctx context.Context, appID AppID, userID UserID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteUserRequest(c.Server, appID, userID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetUser(ctx context.Context, appID AppID, userID UserID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetUserRequest(c.Server, appID, userID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateUserWithBody(ctx context.Context, appID AppID, userID UserID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateUserRequestWithBody(c.Server, appID, userID, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateUser(ctx context.Context, appID AppID, userID UserID, body UpdateUserJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateUserRequest(c.Server, appID, userID, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ActivateUser(ctx context.Context, appID AppID, userID UserID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewActivateUserRequest(c.Server, appID, userID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeactivateUser(ctx context.Context, appID AppID, userID UserID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeactivateUserRequest(c.Server, appID, userID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListUserDevices(ctx context.Context, appID AppID, userID UserID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListUserDevicesRequest(c.Server, appID, userID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteUserDevices(ctx context.Context, appID AppID, userID UserID, deviceID string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteUserDevicesRequest(c.Server, appID, userID, deviceID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RevokeUserRefreshTokens(ctx context.Context, appID AppID, userID UserID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRevokeUserRefreshTokensRequest(c.Server, appID, userID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetAppRequest generates requests for GetApp
func NewGetAppRequest(server string, appID AppID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "app_id", runtime.ParamLocationPath, appID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/apps/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateMagicLinkRequest calls the generic CreateMagicLink builder with application/json body
func NewCreateMagicLinkRequest(server string, appID AppID, body CreateMagicLinkJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateMagicLinkRequestWithBody(server, appID, "application/json", bodyReader)
}

// NewCreateMagicLinkRequestWithBody generates requests for CreateMagicLink with any type of body
func NewCreateMagicLinkRequestWithBody(server string, appID AppID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "app_id", runtime.ParamLocationPath, appID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/apps/%s/magic-links", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewCreateUserRequest calls the generic CreateUser builder with application/json body
func NewCreateUserRequest(server string, appID AppID, body CreateUserJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateUserRequestWithBody(server, appID, "application/json", bodyReader)
}

// NewCreateUserRequestWithBody generates requests for CreateUser with any type of body
func NewCreateUserRequestWithBody(server string, appID AppID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "app_id", runtime.ParamLocationPath, appID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/apps/%s/users", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteUserRequest generates requests for DeleteUser
func NewDeleteUserRequest(server string, appID AppID, userID UserID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "app_id", runtime.ParamLocationPath, appID)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "user_id", runtime.ParamLocationPath, userID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/apps/%s/users/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetUserRequest generates requests for GetUser
func NewGetUserRequest(server string, appID AppID, userID UserID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "app_id", runtime.ParamLocationPath, appID)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "user_id", runtime.ParamLocationPath, userID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/apps/%s/users/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpdateUserRequest calls the generic UpdateUser builder with application/json body
func NewUpdateUserRequest(server string, appID AppID, userID UserID, body UpdateUserJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateUserRequestWithBody(server, appID, userID, "application/json", bodyReader)
}

// NewUpdateUserRequestWithBody generates requests for UpdateUser with any type of body
func NewUpdateUserRequestWithBody(server string, appID AppID, userID UserID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "app_id", runtime.ParamLocationPath, appID)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "user_id", runtime.ParamLocationPath, userID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/apps/%s/users/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PATCH", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewActivateUserRequest generates requests for ActivateUser
func NewActivateUserRequest(server string, appID AppID, userID UserID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "app_id", runtime.ParamLocationPath, appID)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "user_id", runtime.ParamLocationPath, userID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/apps/%s/users/%s/activate", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PATCH", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDeactivateUserRequest generates requests for DeactivateUser
func NewDeactivateUserRequest(server string, appID AppID, userID UserID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "app_id", runtime.ParamLocationPath, appID)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "user_id", runtime.ParamLocationPath, userID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/apps/%s/users/%s/deactivate", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PATCH", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListUserDevicesRequest generates requests for ListUserDevices
func NewListUserDevicesRequest(server string, appID AppID, userID UserID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "app_id", runtime.ParamLocationPath, appID)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "user_id", runtime.ParamLocationPath, userID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/apps/%s/users/%s/devices", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDeleteUserDevicesRequest generates requests for DeleteUserDevices
func NewDeleteUserDevicesRequest(server string, appID AppID, userID UserID, deviceID string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "app_id", runtime.ParamLocationPath, appID)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "user_id", runtime.ParamLocationPath, userID)
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithLocation("simple", false, "device_id", runtime.ParamLocationPath, deviceID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/apps/%s/users/%s/devices/%s", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewRevokeUserRefreshTokensRequest generates requests for RevokeUserRefreshTokens
func NewRevokeUserRefreshTokensRequest(server string, appID AppID, userID UserID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "app_id", runtime.ParamLocationPath, appID)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "user_id", runtime.ParamLocationPath, userID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/apps/%s/users/%s/tokens", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetAppWithResponse request
	GetAppWithResponse(ctx context.Context, appID AppID, reqEditors ...RequestEditorFn) (*GetAppResponse, error)

	// CreateMagicLinkWithBodyWithResponse request with any body
	CreateMagicLinkWithBodyWithResponse(ctx context.Context, appID AppID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateMagicLinkResponse, error)

	CreateMagicLinkWithResponse(ctx context.Context, appID AppID, body CreateMagicLinkJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateMagicLinkResponse, error)

	// CreateUserWithBodyWithResponse request with any body
	CreateUserWithBodyWithResponse(ctx context.Context, appID AppID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateUserResponse, error)

	CreateUserWithResponse(ctx context.Context, appID AppID, body CreateUserJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateUserResponse, error)

	// DeleteUserWithResponse request
	DeleteUserWithResponse(ctx context.Context, appID AppID, userID UserID, reqEditors ...RequestEditorFn) (*DeleteUserResponse, error)

	// GetUserWithResponse request
	GetUserWithResponse(ctx context.Context, appID AppID, userID UserID, reqEditors ...RequestEditorFn) (*GetUserResponse, error)

	// UpdateUserWithBodyWithResponse request with any body
	UpdateUserWithBodyWithResponse(ctx context.Context, appID AppID, userID UserID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateUserResponse, error)

	UpdateUserWithResponse(ctx context.Context, appID AppID, userID UserID, body UpdateUserJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateUserResponse, error)

	// ActivateUserWithResponse request
	ActivateUserWithResponse(ctx context.Context, appID AppID, userID UserID, reqEditors ...RequestEditorFn) (*ActivateUserResponse, error)

	// DeactivateUserWithResponse request
	DeactivateUserWithResponse(ctx context.Context, appID AppID, userID UserID, reqEditors ...RequestEditorFn) (*DeactivateUserResponse, error)

	// ListUserDevicesWithResponse request
	ListUserDevicesWithResponse(ctx context.Context, appID AppID, userID UserID, reqEditors ...RequestEditorFn) (*ListUserDevicesResponse, error)

	// DeleteUserDevicesWithResponse request
	DeleteUserDevicesWithResponse(ctx context.Context, appID AppID, userID UserID, deviceID string, reqEditors ...RequestEditorFn) (*DeleteUserDevicesResponse, error)

	// RevokeUserRefreshTokensWithResponse request
	RevokeUserRefreshTokensWithResponse(ctx context.Context, appID AppID, userID UserID, reqEditors ...RequestEditorFn) (*RevokeUserRefreshTokensResponse, error)
}

type GetAppResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *AppResponse
	JSON401      *N401Error
	JSON404      *N404Error
	JSON500      *N500Error
}

// Status returns HTTPResponse.Status
func (r GetAppResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAppResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateMagicLinkResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *MagicLinkResponse
	JSON400      *N400Error
	JSON401      *N401Error
	JSON404      *N404Error
	JSON500      *N500Error
}

// Status returns HTTPResponse.Status
func (r CreateMagicLinkResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateMagicLinkResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateUserResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *UserResponse
	JSON400      *N400Error
	JSON401      *N401Error
	JSON404      *N404Error
	JSON500      *N500Error
}

// Status returns HTTPResponse.Status
func (r CreateUserResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateUserResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteUserResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON401      *N401Error
	JSON404      *N404Error
	JSON500      *N500Error
}

// Status returns HTTPResponse.Status
func (r DeleteUserResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteUserResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetUserResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *UserResponse
	JSON401      *N401Error
	JSON404      *N404Error
	JSON500      *N500Error
}

// Status returns HTTPResponse.Status
func (r GetUserResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetUserResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UpdateUserResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *UserResponse
	JSON400      *N400Error
	JSON401      *N401Error
	JSON404      *N404Error
	JSON500      *N500Error
}

// Status returns HTTPResponse.Status
func (r UpdateUserResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateUserResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ActivateUserResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *UserResponse
	JSON401      *N401Error
	JSON404      *N404Error
	JSON500      *N500Error
}

// Status returns HTTPResponse.Status
func (r ActivateUserResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ActivateUserResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeactivateUserResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *UserResponse
	JSON401      *N401Error
	JSON404      *N404Error
	JSON500      *N500Error
}

// Status returns HTTPResponse.Status
func (r DeactivateUserResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeactivateUserResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListUserDevicesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ListDevicesResponse
	JSON401      *N401Error
	JSON404      *N404Error
	JSON500      *N500Error
}

// Status returns HTTPResponse.Status
func (r ListUserDevicesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListUserDevicesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteUserDevicesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON401      *N401Error
	JSON404      *N404Error
	JSON500      *N500Error
}

// Status returns HTTPResponse.Status
func (r DeleteUserDevicesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteUserDevicesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type RevokeUserRefreshTokensResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON401      *N401Error
	JSON404      *N404Error
	JSON500      *N500Error
}

// Status returns HTTPResponse.Status
func (r RevokeUserRefreshTokensResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RevokeUserRefreshTokensResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetAppWithResponse request returning *GetAppResponse
func (c *ClientWithResponses) GetAppWithResponse(ctx context.Context, appID AppID, reqEditors ...RequestEditorFn) (*GetAppResponse, error) {
	rsp, err := c.GetApp(ctx, appID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAppResponse(rsp)
}

// CreateMagicLinkWithBodyWithResponse request with arbitrary body returning *CreateMagicLinkResponse
func (c *ClientWithResponses) CreateMagicLinkWithBodyWithResponse(ctx context.Context, appID AppID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateMagicLinkResponse, error) {
	rsp, err := c.CreateMagicLinkWithBody(ctx, appID, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateMagicLinkResponse(rsp)
}

func (c *ClientWithResponses) CreateMagicLinkWithResponse(ctx context.Context, appID AppID, body CreateMagicLinkJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateMagicLinkResponse, error) {
	rsp, err := c.CreateMagicLink(ctx, appID, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateMagicLinkResponse(rsp)
}

// CreateUserWithBodyWithResponse request with arbitrary body returning *CreateUserResponse
func (c *ClientWithResponses) CreateUserWithBodyWithResponse(ctx context.Context, appID AppID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateUserResponse, error) {
	rsp, err := c.CreateUserWithBody(ctx, appID, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateUserResponse(rsp)
}

func (c *ClientWithResponses) CreateUserWithResponse(ctx context.Context, appID AppID, body CreateUserJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateUserResponse, error) {
	rsp, err := c.CreateUser(ctx, appID, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateUserResponse(rsp)
}

// DeleteUserWithResponse request returning *DeleteUserResponse
func (c *ClientWithResponses) DeleteUserWithResponse(ctx context.Context, appID AppID, userID UserID, reqEditors ...RequestEditorFn) (*DeleteUserResponse, error) {
	rsp, err := c.DeleteUser(ctx, appID, userID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteUserResponse(rsp)
}

// GetUserWithResponse request returning *GetUserResponse
func (c *ClientWithResponses) GetUserWithResponse(ctx context.Context, appID AppID, userID UserID, reqEditors ...RequestEditorFn) (*GetUserResponse, error) {
	rsp, err := c.GetUser(ctx, appID, userID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetUserResponse(rsp)
}

// UpdateUserWithBodyWithResponse request with arbitrary body returning *UpdateUserResponse
func (c *ClientWithResponses) UpdateUserWithBodyWithResponse(ctx context.Context, appID AppID, userID UserID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateUserResponse, error) {
	rsp, err := c.UpdateUserWithBody(ctx, appID, userID, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateUserResponse(rsp)
}

func (c *ClientWithResponses) UpdateUserWithResponse(ctx context.Context, appID AppID, userID UserID, body UpdateUserJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateUserResponse, error) {
	rsp, err := c.UpdateUser(ctx, appID, userID, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateUserResponse(rsp)
}

// ActivateUserWithResponse request returning *ActivateUserResponse
func (c *ClientWithResponses) ActivateUserWithResponse(ctx context.Context, appID AppID, userID UserID, reqEditors ...RequestEditorFn) (*ActivateUserResponse, error) {
	rsp, err := c.ActivateUser(ctx, appID, userID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseActivateUserResponse(rsp)
}

// DeactivateUserWithResponse request returning *DeactivateUserResponse
func (c *ClientWithResponses) DeactivateUserWithResponse(ctx context.Context, appID AppID, userID UserID, reqEditors ...RequestEditorFn) (*DeactivateUserResponse, error) {
	rsp, err := c.DeactivateUser(ctx, appID, userID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeactivateUserResponse(rsp)
}

// ListUserDevicesWithResponse request returning *ListUserDevicesResponse
func (c *ClientWithResponses) ListUserDevicesWithResponse(ctx context.Context, appID AppID, userID UserID, reqEditors ...RequestEditorFn) (*ListUserDevicesResponse, error) {
	rsp, err := c.ListUserDevices(ctx, appID, userID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListUserDevicesResponse(rsp)
}

// DeleteUserDevicesWithResponse request returning *DeleteUserDevicesResponse
func (c *ClientWithResponses) DeleteUserDevicesWithResponse(ctx context.Context, appID AppID, userID UserID, deviceID string, reqEditors ...RequestEditorFn) (*DeleteUserDevicesResponse, error) {
	rsp, err := c.DeleteUserDevices(ctx, appID, userID, deviceID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteUserDevicesResponse(rsp)
}

// RevokeUserRefreshTokensWithResponse request returning *RevokeUserRefreshTokensResponse
func (c *ClientWithResponses) RevokeUserRefreshTokensWithResponse(ctx context.Context, appID AppID, userID UserID, reqEditors ...RequestEditorFn) (*RevokeUserRefreshTokensResponse, error) {
	rsp, err := c.RevokeUserRefreshTokens(ctx, appID, userID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRevokeUserRefreshTokensResponse(rsp)
}

// ParseGetAppResponse parses an HTTP response from a GetAppWithResponse call
func ParseGetAppResponse(rsp *http.Response) (*GetAppResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAppResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AppResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest N401Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest N404Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest N500Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseCreateMagicLinkResponse parses an HTTP response from a CreateMagicLinkWithResponse call
func ParseCreateMagicLinkResponse(rsp *http.Response) (*CreateMagicLinkResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateMagicLinkResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest MagicLinkResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest N400Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest N401Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest N404Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest N500Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseCreateUserResponse parses an HTTP response from a CreateUserWithResponse call
func ParseCreateUserResponse(rsp *http.Response) (*CreateUserResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateUserResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest UserResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest N400Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest N401Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest N404Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest N500Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseDeleteUserResponse parses an HTTP response from a DeleteUserWithResponse call
func ParseDeleteUserResponse(rsp *http.Response) (*DeleteUserResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteUserResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest N401Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest N404Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest N500Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetUserResponse parses an HTTP response from a GetUserWithResponse call
func ParseGetUserResponse(rsp *http.Response) (*GetUserResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetUserResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest UserResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest N401Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest N404Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest N500Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseUpdateUserResponse parses an HTTP response from a UpdateUserWithResponse call
func ParseUpdateUserResponse(rsp *http.Response) (*UpdateUserResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateUserResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest UserResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest N400Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest N401Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest N404Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest N500Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseActivateUserResponse parses an HTTP response from a ActivateUserWithResponse call
func ParseActivateUserResponse(rsp *http.Response) (*ActivateUserResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ActivateUserResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest UserResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest N401Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest N404Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest N500Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseDeactivateUserResponse parses an HTTP response from a DeactivateUserWithResponse call
func ParseDeactivateUserResponse(rsp *http.Response) (*DeactivateUserResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeactivateUserResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest UserResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest N401Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest N404Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest N500Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseListUserDevicesResponse parses an HTTP response from a ListUserDevicesWithResponse call
func ParseListUserDevicesResponse(rsp *http.Response) (*ListUserDevicesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListUserDevicesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ListDevicesResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest N401Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest N404Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest N500Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseDeleteUserDevicesResponse parses an HTTP response from a DeleteUserDevicesWithResponse call
func ParseDeleteUserDevicesResponse(rsp *http.Response) (*DeleteUserDevicesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteUserDevicesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest N401Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest N404Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest N500Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseRevokeUserRefreshTokensResponse parses an HTTP response from a RevokeUserRefreshTokensWithResponse call
func ParseRevokeUserRefreshTokensResponse(rsp *http.Response) (*RevokeUserRefreshTokensResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RevokeUserRefreshTokensResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest N401Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest N404Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest N500Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
