name: Create Release

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PASSAGE_APP_ID: ${{ secrets.PASSAGE_APP_ID }}
  PASSAGE_API_KEY: ${{ secrets.PASSAGE_API_KEY }}
  PASSAGE_USER_ID: ${{ secrets.PASSAGE_USER_ID }}
  PASSAGE_AUTH_TOKEN: ${{ secrets.PASSAGE_AUTH_TOKEN }}

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: go test ./...

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read version
        run: |
          echo "VERSION=$(cat version.txt)" >> $GITHUB_ENV

      - name: Check if release is needed
        id: check
        run: |
          _last_version=`git describe --tags --abbrev=0`
          if [[ "$VERSION" == "$_last_version" ]]; then
            # no release needed
            echo ::set-output name=create_release::false
          else
            echo ::set-output name=create_release::true
          fi

      - name: Create Release
        if: ${{ steps.check.outputs.create_release }}
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          draft: false
          prerelease: false
