name: Create Release

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PASSAGE_APP_ID: ${{ secrets.PASSAGE_APP_ID }}
  PASSAGE_API_KEY: ${{ secrets.PASSAGE_API_KEY }}
  PASSAGE_USER_ID: ${{ secrets.PASSAGE_USER_ID }}
  PASSAGE_AUTH_TOKEN: ${{ secrets.PASSAGE_AUTH_TOKEN }}

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: go test ./...

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set version
        run: ./scripts/set-version

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
