name: Run Tests

on:
  workflow_call:
  workflow_dispatch:
  pull_request:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PASSAGE_APP_ID: ${{ secrets.PASSAGE_APP_ID }}
  PASSAGE_API_KEY: ${{ secrets.PASSAGE_API_KEY }}
  PASSAGE_USER_ID: ${{ secrets.PASSAGE_USER_ID }}
  PASSAGE_AUTH_TOKEN: ${{ secrets.PASSAGE_AUTH_TOKEN }}

jobs:
  build:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.14'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: go test ./...

      - name: Test with race detector
        run: go test -race -run TestAppJWKSCacheWriteConcurrency
