name: Lint, Format, and Test

on:
  workflow_call:
  workflow_dispatch:
  pull_request:

env:
  PASSAGE_APP_ID: ${{ secrets.PASSAGE_APP_ID }}
  PASSAGE_API_KEY: ${{ secrets.PASSAGE_API_KEY }}
  PASSAGE_USER_ID: ${{ secrets.PASSAGE_USER_ID }}
  PASSAGE_AUTH_TOKEN: ${{ secrets.PASSAGE_AUTH_TOKEN }}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Format
        run: |
          if [[ $(gofmt -s -d .) ]]; then
            echo "Run 'gofmt -s -w .' to format code."
            exit 1
          fi
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Test
        run: go test ./...
      - name: Test with race detector
        run: go test -race -run TestAppJWKSCacheWriteConcurrency
